name: hero_animation
description: Shows how to create a simple Hero transition.

environment:
  sdk: '>=2.17.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.2
  http: ^0.13.5
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/locations.json